import mongoose from "mongoose";

export const products = [
  {
    _id: new mongoose.Types.ObjectId(),
    title: "iPhone 9",
    description: "An apple mobile which is nothing like apple",
    price: 899,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "iphone9.jpg",
    createdAt: 1115211422,
    updatedAt: 1115211422,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Samsung Universe 9",
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    price: 1249,
    brand: "Samsung",
    category: "smartphones",
    thumbnail: "samsung9.jpg",
    createdAt: 1115211422,
    updatedAt: 1115211422,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Huawei P30",
    description:
      "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
    price: 499,
    brand: "Huawei",
    category: "smartphones",
    thumbnail: "huaweiP30.jpg",
    createdAt: 1595589072,
    updatedAt: 1595589072,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Microsoft Surface Laptop 4",
    description:
      "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
    price: 1499,
    brand: "Microsoft",
    category: "laptops",
    thumbnail: "microsoftSurface4.jpg",
    createdAt: 1493463661,
    updatedAt: 1493463661,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "HP Pavilion 15-DK1056WM",
    description:
      "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
    price: 1099,
    brand: "HP",
    category: "laptops",
    thumbnail: "hpPavilion15.jpg",
    createdAt: 1595589072,
    updatedAt: 1595589072,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Fog Scent Xpressio Perfume",
    description:
      "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
    price: 13,
    brand: "Foq Scent Xpressio",
    category: "fragrances",
    thumbnail: "FoqScentXpressio.jpg",
    createdAt: 1115211422,
    updatedAt: 1115211422,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Hyaluronic Acid Serum",
    description:
      "L'Oreal Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
    price: 19,
    brand: "L'Oreal Paris",
    category: "skincare",
    thumbnail: "HyaluronicAcidSerum.jpg",
    createdAt: 1115211422,
    updatedAt: 1115211422,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Freckle Treatment Cream",
    description:
      "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects",
    price: 70,
    brand: "Fair & Clear",
    category: "skincare",
    thumbnail: "FreckleTreatmentCream.jpg",
    createdAt: 1595589072,
    updatedAt: 1595589072,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Orange Essence Food Flavour",
    description:
      "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item",
    price: 14,
    brand: "Baking Food Items",
    category: "groceries",
    thumbnail: "OrangeEssenceFoodFlavour.jpg",
    createdAt: 1493463661,
    updatedAt: 1493463661,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Gulab Powder",
    description: "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
    price: 69,
    brand: "Dry Rose",
    category: "groceries",
    thumbnail: "GulabPowder.jpg",
    createdAt: 1115211422,
    updatedAt: 1115211422,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Flying Wooden Bird",
    description:
      "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm",
    price: 51,
    brand: "Flying Wooden",
    category: "home decoration",
    thumbnail: "FlyingWoodenBird.jpg",
    createdAt: 1115211422,
    updatedAt: 1115211422,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Handcraft Chinese style",
    description:
      "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
    price: 60,
    brand: "Luxury Palace",
    category: "home decoration",
    thumbnail: "HandcraftChineseStyle.jpg",
    createdAt: 1595589072,
    updatedAt: 1595589072,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Mornadi Velvet Bed",
    description:
      "Mornadi Velvet Bed Base with Headboard Slats Support Classic Style Bedroom Furniture Bed Set",
    price: 40,
    brand: "Furniture Bed Set",
    category: "furniture",
    thumbnail: "MornadiVelvetBed.jpg",
    createdAt: 1595589072,
    updatedAt: 1595589072,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Plastic Table",
    description:
      "Very good quality plastic table for multi purpose now in reasonable price",
    price: 50,
    brand: "Multi Purpose",
    category: "furniture",
    thumbnail: "PlasticTable.jpg",
    createdAt: 1493463661,
    updatedAt: 1493463661,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Sleeve Shirt Women's",
    description:
      "Cotton Solid Color Professional Wear Sleeve Shirt Women's Work Blouses Wholesale Clothing Casual Plain Custom Top OEM Customized",
    price: 113,
    brand: "Professional Wear",
    category: "tops",
    thumbnail: "SleeveShirtWomen.jpg",
    createdAt: 1595589072,
    updatedAt: 1595589072,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Sublimation Plain Kids Tank",
    description: "Sublimation plain kids tank tops wholesale",
    price: 23,
    brand: "Soft Cotton",
    category: "tops",
    thumbnail: "SublimationPlainKidsTank.jpg",
    createdAt: 1115211422,
    updatedAt: 1115211422,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Leather Straps Wristwatch",
    description: "Style:Sport ,Clasp:Buckles ,Water Resistance Depth:3Bar",
    price: 120,
    brand: "Naviforce",
    category: "watches",
    thumbnail: "LeatherStrapsWristwatch.jpg",
    createdAt: 1595589072,
    updatedAt: 1595589072,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Fashion Magnetic Wrist Watch",
    description:
      "Buy this awesome  The product is originally manufactured by the company and it's a top selling product with a very reasonable",
    price: 70,
    brand: "Eastern Watches",
    category: "watches",
    thumbnail: "FashionMagneticWristWatch.jpg",
    createdAt: 1493463661,
    updatedAt: 1493463661,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Silver Ring Set",
    description:
      "Fashion Jewellery 3Pcs Adjustable Pearl Rhinestone Korean Style Open Rings For Women",
    price: 70,
    brand: "Darojay",
    category: "jewelry",
    thumbnail: "SilverRingSet.jpg",
    createdAt: 1595589072,
    updatedAt: 1595589072,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Rose Ring",
    description:
      "The Greetings Flower Colour: RedRing Colour: GoldenSize: Adjustable",
    price: 100,
    brand: "Copenhagen Lux",
    category: "jewelry",
    thumbnail: "RoseRing.jpg",
    createdAt: 1115211422,
    updatedAt: 1115211422,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Wiley X Night Vision",
    description:
      "Wiley X Night Vision Yellow Glasses for Riders - Night Vision Anti Fog Driving Glasses - Free Night Glass Cover - Shield Eyes From Dust and Virus- For Night Sport Matches",
    price: 30,
    brand: "Mastar Watch",
    category: "sunglasses",
    thumbnail: "WileyXNightVision.jpg",
    createdAt: 1493463661,
    updatedAt: 1493463661,
    __v: 0,
  },
  {
    _id: new mongoose.Types.ObjectId(),
    title: "Square Sunglasses",
    description:
      "Fashion Oversized Square Sunglasses Retro Gradient Big Frame Sunglasses For Women One Piece Gafas Shade Mirror Clear Lens 17059",
    price: 28,
    brand: "Mastar Watch",
    category: "sunglasses",
    thumbnail: "SquareSunglasses.jpg",
    createdAt: 1595589072,
    updatedAt: 1595589072,
    __v: 0,
  },
];
